theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "docker"
interval = 2
format = "{running}|{stopped}|{total}"

[[block]]
block = "uptime"

[[block]]
block = "net"
device = "enp0s3"
ssid = true
signal_strength = true
ip = true
interval = 5

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mum}MB/{MTm}MB({Mup}%)"
icons = true
clickable = true
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
block = "battery"
interval = 10
format = "{percentage}%"


[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
